name: meal_plan_final_app
description: A full Flutter meal planner app with drawer and weekly plan.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0                             
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  provider: ^6.1.2
  flutter_bloc: ^9.1.1
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
